data:extend({
    {
        order = "1",
        name = "BuildWithoutRhythm-block-inserters",
        type = "int-setting",
        setting_type = "runtime-global",
        default_value = 300,
        minimum_value = 0,
    },
    {
        order = "2",
        name = "BuildWithoutRhythm-block-assemblers",
        type = "int-setting",
        setting_type = "runtime-global",
        default_value = 300,
        minimum_value = 0,
    },
    {
        order = "3",
        name = "BuildWithoutRhythm-block-power-poles",
        type = "int-setting",
        setting_type = "runtime-global",
        default_value = 300,
        minimum_value = 0,
    },
    {
        order = "4",
        name = "BuildWithoutRhythm-block-solar-panels",
        type = "int-setting",
        setting_type = "runtime-global",
        default_value = 300,
        minimum_value = 0,
    },
    {
        order = "5",
        name = "BuildWithoutRhythm-block-furnaces",
        type = "int-setting",
        setting_type = "runtime-global",
        default_value = 300,
        minimum_value = 0,
    },
})